"""
ROADMAP: Feature Extraction Pipeline & PyMDMA Functions

This document traces the complete data flow from raw time series to final metrics.
"""

print("="*100)
print("COMPLETE DATA FLOW & FEATURE EXTRACTION ROADMAP")
print("="*100)
print()

print("STEP 1: DATA INPUT")
print("-" * 100)
print()
print("Input format: CSV files in long format")
print("  Columns: ['unique_id', 'ds', 'y']")
print("  Example:")
print("    unique_id | ds         | y")
print("    ----------|------------|---------")
print("    ID1       | 1975-07-31 | 61.61")
print("    ID1       | 1975-08-31 | 66.74")
print("    ID2       | 1975-07-31 | 45.20")
print()

print("File location: assets/results/training_sets/")
print("Examples:")
print("  * Gluonts_m1_monthly_original.csv     (real data)")
print("  * Gluonts_m1_monthly_GrasyndaE.csv    (synthetic data with original mixed in)")
print()

print()
print("STEP 2: DATA TRANSFORMATION")
print("-" * 100)
print()

print("Function: df_to_array()")
print("  Location: run_pymdma_eval_corrected.py, line ~44")
print()
print("  Input:")
print("    pd.DataFrame with columns ['unique_id', 'ds', 'y']")
print("    Example shape: (35232, 3) - one row per unique_id-timestamp pair")
print()
print("  Process:")
print("    1. pivot(index='ds', columns='unique_id', values='y')")
print("       -> Matrix shape: (n_timestamps, n_series)")
print("       -> Example: (452, 468) for Gluonts_m1_monthly")
print()
print("    2. ffill().bfill() - Fill missing values")
print()
print("    3. .T.values - Transpose to get (n_series, n_timestamps)")
print()
print("  Output:")
print("    np.ndarray shape (n_series, series_length)")
print("    Example: (468, 452) for Gluonts_m1_monthly")
print("    Values: raw time series values")
print()

print()
print("STEP 3: SYNTHETIC DATA SEPARATION (CRITICAL FIX)")
print("-" * 100)
print()

print("Function: get_only_synthetic()")
print("  Location: run_pymdma_eval_corrected.py, line ~107")
print()
print("  Input:")
print("    synth_df: DataFrame with 936 series (468 original + 468 synthetic)")
print("    real_df: DataFrame with 468 series (original only)")
print()
print("  Process:")
print("    real_ids = set(real_df['unique_id'].unique())")
print("    synth_only = synth_df[~synth_df['unique_id'].isin(real_ids)].copy()")
print()
print("  Output:")
print("    Filtered DataFrame with ONLY the 468 NEW synthetic series")
print("    (Removes the 468 original series that were mixed in)")
print()

print()
print("STEP 4: FEATURE EXTRACTION")
print("-" * 100)
print()

print("Function: extract_features()")
print("  Location: run_pymdma_eval_corrected.py, line ~84")
print()
print("  Input:")
print("    np.ndarray shape (n_series, series_length)")
print("    Example: (468, 452)")
print()
print("  Process:")
print("    IF tsfel available:")
print("      -> Use extract_features_tsfel()")
print("    ELSE:")
print("      -> Use extract_features_fallback()")
print()

print()
print("  OPTION A: extract_features_tsfel()")
print("  " + "-" * 96)
print()
print("  Library: TSFEL (Time Series Feature Extraction Library)")
print("  Installation: pip install tsfel")
print()
print("  Function call:")
print("    cfg = tsfel.get_features_by_domain('temporal')")
print("    -> Returns configuration for temporal domain features")
print()
print("  Feature extraction loop:")
print("    for each time series in data:")
print("      features = tsfel.time_series_features_extractor(cfg, ts, fs=12, verbose=0)")
print()
print("  Input parameters to tsfel:")
print("    * cfg: TSFEL feature configuration")
print("    * ts: 1D numpy array of shape (series_length,)")
print("    * fs: sampling frequency = 12 (monthly data)")
print("    * verbose: 0 (no output)")
print()
print("  Output for EACH series:")
print("    DataFrame with 14 temporal features:")
print()
print("    1. Mean                  (central tendency)")
print("    2. Std Dev              (variability)")
print("    3. Min                  (extremum)")
print("    4. Max                  (extremum)")
print("    5. Median               (central tendency)")
print("    6. IQR                  (spread)")
print("    7. Skewness             (asymmetry)")
print("    8. Kurtosis             (tail behavior)")
print("    9. Autocorrelation@1    (temporal pattern)")
print("   10. Autocorrelation@2    (temporal pattern)")
print("   11. [Other temporal features]")
print()
print("  Shape per series: (1, 14) -> flatten to (14,)")
print()
print("  Final output:")
print("    np.ndarray shape (n_series, 14)")
print("    Example: (468, 14) for Gluonts_m1_monthly")
print()

print()
print("  OPTION B: extract_features_fallback()")
print("  " + "-" * 96)
print()
print("  Lightweight alternative (if tsfel not available)")
print()
print("  Features extracted (7 total):")
print("    1. Mean               = np.nanmean(ts)")
print("    2. Std Dev            = np.nanstd(ts)")
print("    3. Median             = np.nanmedian(ts)")
print("    4. IQR                = Q75 - Q25")
print("    5. Skewness           = pd.Series(ts).skew()")
print("    6. Kurtosis           = pd.Series(ts).kurt()")
print("    7. ACF@lag1           = autocorrelation at lag 1")
print()
print("  Final output:")
print("    np.ndarray shape (n_series, 7)")
print()

print()
print("STEP 5: PYMDMA METRIC COMPUTATION")
print("-" * 100)
print()

print("Function: compute_pymdma_metrics()")
print("  Location: run_pymdma_eval_corrected.py, line ~127")
print()
print("  Input:")
print("    real_feats: np.ndarray shape (n_real, n_features)    # Real features")
print("    synth_feats: np.ndarray shape (n_synth, n_features)  # Synthetic features")
print()
print("    IMPORTANT: Must have >= 7 samples (k-NN default uses k=6)")
print("    Example:")
print("      real_feats shape: (468, 14)    - 468 samples, 14 TSFEL features")
print("      synth_feats shape: (468, 14)   - 468 samples, 14 TSFEL features")
print()

print()
print("  METRIC 1: ImprovedPrecision")
print("  " + "-" * 96)
print()
print("  PyMDMA Function:")
print("    from pymdma.time_series.measures.synthesis_val import ImprovedPrecision")
print()
print("  Usage:")
print("    precision = ImprovedPrecision()")
print("    result = precision.compute(real_feats, synth_feats)")
print()
print("  Input parameters:")
print("    real_feats: np.ndarray shape (n_samples, n_features)")
print("      -> Our case: (468, 14)")
print("      -> Samples: number of time series")
print("      -> Features: 14 TSFEL temporal features")
print()
print("    synth_feats: np.ndarray shape (n_samples, n_features)")
print("      -> Our case: (468, 14)")
print("      -> SAME shape as real_feats")
print()
print("  Algorithm (internally):")
print("    1. Computes nearest neighbor distances in feature space")
print("    2. For each synthetic sample:")
print("       - Find distance to nearest real feature vector")
print("       - Check if within k-NN radius of real distribution")
print("    3. Precision = float in [0.0, 1.0]")
print()
print("  Output:")
print("    MetricResult object with:")
print("    * .value = tuple of length 2")
print("      [0] dataset_level: float in [0.0, 1.0] (SCALAR)")
print("      [1] instance_level: list[int] of length 468 (per-sample, 0 or 1)")
print()
print("  Our extraction:")
print("    precision_value = metric_result.value[0]  # Take float (dataset-level)")
print()

print()
print("  METRIC 2: ImprovedRecall")
print("  " + "-" * 96)
print()
print("  PyMDMA Function:")
print("    from pymdma.time_series.measures.synthesis_val import ImprovedRecall")
print()
print("  Usage:")
print("    recall = ImprovedRecall()")
print("    result = recall.compute(real_feats, synth_feats)")
print()
print("  Input parameters: SAME as ImprovedPrecision")
print("    real_feats: np.ndarray shape (n_samples, n_features) = (468, 14)")
print("    synth_feats: np.ndarray shape (n_samples, n_features) = (468, 14)")
print()
print("  Algorithm (internally):")
print("    1. Computes nearest neighbor distances in feature space")
print("    2. For each real sample:")
print("       - Find distance to nearest synthetic feature vector")
print("       - Check if within k-NN radius of synthetic distribution")
print("    3. Recall = float in [0.0, 1.0]")
print()
print("  Output:")
print("    MetricResult object with:")
print("    * .value = tuple of length 2")
print("      [0] dataset_level: float in [0.0, 1.0] (SCALAR)")
print("      [1] instance_level: list[int] of length 468 (per-sample, 0-k distances)")
print()
print("  Our extraction:")
print("    recall_value = metric_result.value[0]  # Take float (dataset-level)")
print()

print()
print("STEP 6: RESULTS AGGREGATION")
print("-" * 100)
print()

print("Function: evaluate_all()")
print("  Location: run_pymdma_eval_corrected.py, line ~145")
print()
print("  Process:")
print("    For each dataset:")
print("      1. Load real data")
print("      2. Extract features -> shape (n_real, 14)")
print("      3. For each synthetic method:")
print("         a. Load synthetic data (468 original + 468 synthetic)")
print("         b. Remove original -> get_only_synthetic()")
print("         c. Extract features -> shape (n_synth_pure, 14)")
print("         d. Compute precision & recall")
print("         e. Store results")
print("      4. Save per-dataset CSV")
print("    5. Save aggregate JSON")
print()

print()
print("="*100)
print("COMPLETE CALL SEQUENCE")
print("="*100)
print()

sequence = """
main()
  |
  +- For each dataset:
      |
      +- real_df = pd.read_csv(original.csv)
      |
      +- real_data = df_to_array(real_df)
      |   +- Output: np.ndarray (468, 452)
      |
      +- real_feats = extract_features(real_data)
      |   |
      |   +- EITHER:
      |       +- cfg = tsfel.get_features_by_domain('temporal')
      |       +- tsfel.time_series_features_extractor(cfg, ts, fs=12)
      |           +- Output: np.ndarray (468, 14)
      |       OR:
      |       +- extract_features_fallback()
      |           +- Output: np.ndarray (468, 7)
      |
      +- For each synthetic method:
          |
          +- synth_df = pd.read_csv(method.csv)
          |
          +- synth_only_df = get_only_synthetic(synth_df, real_df)
          |   +- Output: DataFrame with only 468 NEW synthetic series
          |
          +- synth_data = df_to_array(synth_only_df)
          |   +- Output: np.ndarray (468, 452)
          |
          +- synth_feats = extract_features(synth_data)
          |   +- Output: np.ndarray (468, 14) or (468, 7)
          |
          +- precision = ImprovedPrecision().compute(real_feats, synth_feats)
          |   +- Output: MetricResult.value[0] = float (0-1)
          |
          +- recall = ImprovedRecall().compute(real_feats, synth_feats)
          |   +- Output: MetricResult.value[0] = float (0-1)
          |
          +- Store {method: {precision: X, recall: Y}}
"""

print(sequence)

print()
print("="*100)
print("SUMMARY TABLE: Functions & Their I/O")
print("="*100)
print()

print("Function            | Input Shape     | Output Type")
print("-" * 100)
print("df_to_array()       | DF(n,3)         | ndarray(468, 452) - raw time series")
print("get_only_synthetic()| DF(n,3)         | DF(n',3) - 468 pure synthetic series")
print("extract_features_   | ndarray(468,452)| ndarray(468, 14) - 14 TSFEL features")
print("  tsfel()           | raw ts          |")
print("extract_features_   | ndarray(468,452)| ndarray(468, 7) - 7 basic statistics")
print("  fallback()        | raw ts          |")
print("ImprovedPrecision.  | real_feats(468,14) | MetricResult")
print("  compute()         | synth_feats(468,14)|   .value[0] = float (0.0-1.0)")
print("                    |                  |   .value[1] = list[int] (468 items)")
print("ImprovedRecall.     | real_feats(468,14) | MetricResult")
print("  compute()         | synth_feats(468,14)|   .value[0] = float (0.0-1.0)")
print("                    |                  |   .value[1] = list[int] (468 items)")
print()

print()
print("="*100)
print("KEY INSIGHTS")
print("="*100)
print()

print("1. TSFEL FEATURES (14 total):")
print("   - Temporal domain only (not frequency domain)")
print("   - Captures mean, variance, ACF, skewness, kurtosis")
print("   - fs=12 means assuming monthly data")
print()

print("2. FALLBACK FEATURES (7 total):")
print("   - Mean, Std, Median, IQR, Skew, Kurt, ACF@lag1")
print("   - Lightweight alternative if tsfel unavailable")
print()

print("3. PYMDMA METRIC OUTPUTS - CRITICAL DETAIL:")
print("   - RETURN: MetricResult object with .value = (dataset_level, instance_level)")
print("   - dataset_level: FLOAT scalar in [0.0, 1.0]")
print("      ImprovedPrecision: fraction of synth samples within real distribution")
print("      ImprovedRecall: fraction of real samples within synth distribution")
print("   - instance_level: LIST of per-sample values")
print("      ImprovedPrecision: [0 or 1] x 468 (binary per sample)")
print("      ImprovedRecall: [0-20] x 468 (distance counts per sample)")
print()

print("4. DATA FLOW WITH CORRECT SHAPES:")
print("   CSV file (long format)")
print("   -> df_to_array()")
print("   -> ndarray (468, 452)     [468 series, 452 timestamps]")
print("   -> extract_features()")
print("   -> ndarray (468, 14)      [468 series, 14 TSFEL features]")
print("   -> ImprovedPrecision.compute(real_feats, synth_feats)")
print("   -> MetricResult.value = (0.961, [1,1,0,1,...,0,1])")
print()

print("5. MINIMUM SAMPLE REQUIREMENT:")
print("   - PyMDMA uses k-NN with k=6 by default")
print("   - Must have at least 7 samples in dataset")
print("   - Our datasets have 365-799 series -> SAFE")
print()
